### ISSUE TITLE
Don't use CopyIfChanged in GeneratePkgDef target

### ISSUE THREAD

**Issue by garuma** [xamarin/Xamarin.VSSDK#25]
It perma-breaks dependency resolution because the timestamp of the output file is never reset. This means that the target will always run because Inputs are always considered newer than Outputs.

**Comment by kzu** [comment]
The target is *literally* a copy of the built-in VSSDK target of the same name, with the only addition that 
it filters the @(ReferencePath) to exclude facades and framework assemblies. Current (v15.7.109) version 
of the VSSDK target is:

```
  <Target Name="GeneratePkgDef"
          Inputs="$(CreatePkgDefAssemblyToProcess)"
          Outputs="$(IntermediateOutputPath)$(TargetName).pkgdef"
          Condition="'$(GeneratePkgDefFile)'=='true'"
          DependsOnTargets="$(GeneratePkgDefDependsOn)">

    <Message Text="Creating intermediate PkgDef file." />

    <CreatePkgDef AssemblyToProcess="$(CreatePkgDefAssemblyToProcess)"
                  ProductVersion="$(TargetVSVersion)"
                  OutputFile="$(IntermediateOutputPath)$(TargetName).latest.pkgdef"
                  UseCodebase="$(UseCodebase)"
                  ReferencedAssemblies="@(ReferencePath)"  />
    <CopyIfChanged Condition="Exists('$(IntermediateOutputPath)$(TargetName).latest.pkgdef')"
                   SourceFile="$(IntermediateOutputPath)$(TargetName).latest.pkgdef"
                   DestinationFile="$(IntermediateOutputPath)$(TargetName).pkgdef" />

    <!-- If the CTO file was changed, touch the pkgdef file to cause a re-merge -->
    <Touch Files="$(IntermediateOutputPath)$(TargetName).pkgdef"
           Condition="'$(CTOFileHasChanged)'=='true' AND Exists('$(IntermediateOutputPath)$(TargetName).pkgdef')" />

    <ItemGroup>
      <FileWrites Include="$(IntermediateOutputPath)$(TargetName).pkgdef" Condition="Exists('$(IntermediateOutputPath)$(TargetName).pkgdef')"/>
      <FileWrites Include="$(IntermediateOutputPath)$(TargetName).latest.pkgdef" Condition="Exists('$(IntermediateOutputPath)$(TargetName).latest.pkgdef')"/>
    </ItemGroup>
```

So if this is indeed the case, it should be reported via devdiv so it can be fixed in the VSSDK itself.
Also, note that the CopyIfChanged task implementation does not use timestamps to compare. It will actually compare file length AND its entire content to determine if it needs to be copied. So it will only overwrite the target pkgdef if the input assembly changes. 

Does it make sense?

**Comment by garuma** [comment]
Yep, but that's what I described in my PR comment as you can have a more recent input that produces the same output. As a result you break the invariant that your `Outputs` have to be equal or more recent than your `Inputs` in timestamps after the target executes. Breaking this ends up retriggering all sorts of stuff down the line.

**Comment by kzu** [comment]
I still don't see how, honestly, since any other targets that run after
would still have whichever pkgdef was last valid. Don't recall other
targets that depend on the pkgdef in particular either, would need to dig
deeper.

Again, if this breaks stuff, this would be reported as a devdiv issue for
the VSSDK itself. @madskristensen was keen on us just sending PRs against
the VSSDK for some things we have here that would be generally useful.

**Comment by kzu** [comment]
@garuma is this still an issue? Should we report it as a workitem/feedback ticket? See current VSSDK source at https://dev.azure.com/devdiv/DevDiv/_git/VSExtensibility?path=%2Fsrc%2Fproduct%2Fvssdk%2Fmsbuild%2FMicrosoft.VisualStudio.Sdk.BuildTasks.16.0%2FTargets%2FMicrosoft.VsSDK.targets&version=GBdevelop&line=1139&lineEnd=1165&lineStartColumn=1&lineEndColumn=1&lineStyle=plain

**Comment by garuma** [comment]
I'm a little fuzzy on this one but re-reading myself and looking at your link it sounds like it's indeed still a problem

**Comment by kzu** [comment]
I've now removed this target on our side since the VSSDK now works without breaking with large amounts of nuget/references.
